services:
  frontend:
    build:
      context: ./frontend/
      target: prod
    profiles:
      - prod
  frontend-dev:
    hostname: frontend
    build:
      context: ./frontend/
      target: dev
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
    profiles:
      - dev
  backend:
    build:
      context: ./backend/
      target: prod
    profiles:
      - prod
  backend-dev:
    hostname: backend
    build:
      context: ./backend/
      target: dev
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
    profiles:
      - dev
  nginx:
    image: nginx:1.27.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80